<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Uncomment the following line to activate a bug in the WIMP app that causes order rejections -->
    <!--<DefineConstants>$(DefineConstants);SIMULATED_OREDER_REJECTION</DefineConstants>-->
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\..\Shared\WIMP.App\Program.cs" Link="Program.cs" />
    <Compile Include="..\..\..\..\Shared\WIMP.App\Data\*.cs" Link="Data\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\..\..\Shared\WIMP.App\Models\**\*.cs" Link="Models\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\..\..\Shared\WIMP.App\RestApi\**\*.cs" Link="RestApi\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\..\..\Shared\WIMP.App\Services\**\*.cs" Link="Services\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
