# default app settings
app.market.currency=USD
app.market.tax=6.0

spring.jpa.hibernate.ddl-auto=update
# Use H2 in-memory stub database by default, check 'application-prod.properties' for using real database.
# Normally there should be no default setting for the database connection, to enforce explicit selection of the right
# database (e.g. by selecting a profile). We apply the defaults for the sake of simple usage of samples.
spring.datasource.url=jdbc:h2:mem:wimp-db
spring.datasource.username=sa
spring.datasource.password=

# sample app setting: disables checking that the pizza to be ordered is on the menu
app.backdoor.disable-menu-integrity-check=true
# sample app setting: allows overriding the order times instead of taking them from time service
app.backdoor.allow-overriding-order-times=true
