# For prod, a real MySQL database can be used. To use the app with the settings below, start a Docker container with
#   docker run --name wimp-mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=wimp_db -p 3306:3306 -d mysql:8.4
spring.datasource.url=jdbc:mysql://localhost:3306/wimp_db
spring.datasource.username=root
spring.datasource.password=root
