/*
 * NOTE: This application ("WIMP - Where Is My Pizza") is provided solely to
 * demonstrate the Behavior-Driven Development scenario automation patterns
 * described in the book "Effective Behavior-Driven Development" by
 * Gaspar Nagy and Seb Rose.
 *
 * It is NOT a complete or production-ready implementation. It deliberately
 * uses shortcuts and simplifications (e.g. authentication, data storage,
 * error handling, security) that are NOT suitable for a real application.
 * Do not use this code as a basis for production software.
 */

/*
 * NOTE: This application ("WIMP - Where Is My Pizza") is provided solely to
 * demonstrate the Behavior-Driven Development scenario automation patterns
 * described in the book "Effective Behavior-Driven Development" by
 * Gaspar Nagy and Seb Rose.
 *
 * It is NOT a complete or production-ready implementation. It deliberately
 * uses shortcuts and simplifications (e.g. authentication, data storage,
 * error handling, security) that are NOT suitable for a real application.
 * Do not use this code as a basis for production software.
 */

// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WIMP.App.Data;
using WIMP.App.Data.Db;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(WimpDbContext))]
    partial class WimpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WIMP.App.Data.DbRecords.CouponDbRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CODE");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("CUSTOMER_EMAIL");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("SENT_AT");

                    b.HasKey("Id");

                    b.ToTable("COUPON", (string)null);
                });

            modelBuilder.Entity("WIMP.App.Data.DbRecords.CustomerDbRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("CUSTOMER", (string)null);
                });

            modelBuilder.Entity("WIMP.App.Data.DbRecords.DailyPizzaSalesDbRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("DATE");

                    b.Property<string>("Pizza")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PIZZA");

                    b.Property<decimal>("Sales")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("SALES");

                    b.HasKey("Id");

                    b.ToTable("DAILY_PIZZA_SALES", (string)null);
                });

            modelBuilder.Entity("WIMP.App.Data.DbRecords.MenuDbRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME");

                    b.Property<int>("Calories")
                        .HasColumnType("int")
                        .HasColumnName("CAL");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRICE");

                    b.Property<bool>("Vegetarian")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("VEG");

                    b.HasKey("Name");

                    b.ToTable("MENU", (string)null);
                });

            modelBuilder.Entity("WIMP.App.Data.DbRecords.NotificationDbRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CUSTOMER_NAME");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("MESSAGE");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("SENT_AT");

                    b.HasKey("Id");

                    b.ToTable("NOTIFICATION", (string)null);
                });

            modelBuilder.Entity("WIMP.App.Data.DbRecords.OrderDbRecord", b =>
                {
                    b.Property<int>("OrderNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ORDER_NO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderNo"));

                    b.Property<string>("CollectionDetailsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("COLLECTION_DETAILS_JSON");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("CUSTOMER_EMAIL");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CUSTOMER_NAME");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("DELIVERY_ADDRESS");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int")
                        .HasColumnName("DELIVERY_METHOD");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ITEMS_JSON");

                    b.Property<TimeSpan>("PlacingTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("PLACING_TIME");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("PRICE");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("STATUS_MESSAGE");

                    b.HasKey("OrderNo");

                    b.ToTable("ORDER_DATA", (string)null);
                });

            modelBuilder.Entity("WIMP.App.Data.DbRecords.PromotionDbRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("PROMOTION", (string)null);
                });

            modelBuilder.Entity("WIMP.App.Data.DbRecords.SessionDbRecord", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("TOKEN");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CUSTOMER_NAME");

                    b.HasKey("Token");

                    b.ToTable("SESSION", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
